### PR TITLE
BugzId: 61140 

### PR DESCRIPTION
**Pull request by yanglei99**
The changes are in the following areas:
1. Distribute save across RDD partitions, which enables a better parallelism when RDD are distributed cross multiple nodes. Removed jsonstore.rdd.concurrentSave
2. Add and config thread-pool-dispatcher which enables 3X throughput for my test case of 800k records write.
3. Share ActorSystem across the duration of job. You need to do sparkconext.stop() for test to finish
4. fix NPE for CloudantApp.py caused by null returned from getConfig
5. Better exception when save failed. The reason is in the exception message

No need of special tests as any test cases with write path will hit the changed code. Have run without regression of CloudantDF.py, CloudantDFOption.py, CloudantApp.py. 

BugzId: 61140 (https://cloudant.fogbugz.com/f/cases/61140/improve-save-parallelism-sharing-actorSystem-for-the-duration-of-the-job)

### CODE REVIEW

**Comment by mayya-sharipova** [comment]
@yanglei99  The code works well.  All examples are working well. The only problem is with running tests  (they possible need to be modified to include `sparkContext.stop()`), because right now they just freeze for me.  After correcting tests +1 from me.

**Comment by ykye** [comment]
@yanglei99 The `cloudant-spark-sql` code looks good for me. +1 for these changes.

I think there are two issues for improvement:
1). Need to stop the sparkContext in the test-scripts.
2). Need to stop the sparkContext in the scala examples.

**Comment by yanglei99** [comment]
Can we accept the pull request then open a new  issue to make change to the test?

**Comment by HolgerKache** [comment]
@yanglei99 I was trying to amend your PR to add the necessary changes for the test cases and README. However, this is your private fork and I have no permissions to do so.

For that reason, please go ahead and merge the PR after a rebase. I noticed a number of conflicts by now as your fork is stale for a while already. Please ping me when you have the merge completed so I can create a branch and deliver the needed changes to the test cases.

In the future I would appreciate if you can work off a branch in cloudant-labs/spark-cloudant so we can all check out your work and add commits as needed. Thank you!

**Comment by mayya-sharipova** [comment]
@yanglei99  Yang Lei, please rebase your branch against the master, and after that I can modify the tests to reflect your changes

**Comment by yanglei99** [comment]
@mayya-sharipova , If you can do it that will be great! i am in the middle of some benchmark work, will need some more time before I can take care of the pull request. Thank you!

**Comment by mayya-sharipova** [comment]
@yanglei99 Thanks Yang Lei! I will create a branch on https://github.com/cloudant-labs/spark-cloudant from your patch, and will rebase it against master.

**Comment by mayya-sharipova** [comment]
@yanglei99  I have opened a new PR https://github.com/cloudant-labs/spark-cloudant/pull/54, that integrates your changes to the commits that we have already done. I have asked Kang Ye to review it, but please feel free to review it as well.

Do you mind if I close this pull request?

**Comment by mayya-sharipova** [comment]
@yanglei99 Yang Lei, we are closing this Pull Request. We have got a new one https://github.com/cloudant-labs/spark-cloudant/pull/56, which has been merged to master. It contains your commits which were cherry-picked on master  branch.

**Pull request closed without merging**
