### PR TITLE
Handle the exception when cloudant.host or cloudant.username or cloudant.password aren't supplied

### PR DESCRIPTION
**Pull request by ykye**
The connector will throw a exception if user haven't supplied cloudant.host, cloudant.username and cloudant.password. 
Introduced a check in JsonStoreConfigManager.getConfig() and provide a better error message if the user haven't supplied all the three paramters.

BugzID: 59433

@HolgerKache @mayya-sharipova

### CODE REVIEW

**Comment by ykye** [comment]
Yes, the "username" and the "password" aren't mandatory. I have modified the code. Thank you Mayya!

**Comment by mayya-sharipova** [comment]
@ykye Hi Kang Ye, this code produces an error for me : py4j.protocol.Py4JJavaError: An error occurred while calling o26.load.
: java.lang.RuntimeException: Database movies doesn't have any non-design documents!

Have you tested this code? Did it work for you?

**Comment by ykye** [comment]
@mayya-sharipova Hi Mayya, Thanks for reviewing this PR. Yes, It works well. It will throw this exception if the database is empty or just contains design documents. Your database is empty? Is there any non-design documents in your databse(movies)?

**Comment by mayya-sharipova** [comment]
+1 for this commit Kang Ye.  You can merge it. Please add BugzID in the commit message. If you do: "git log", you should see the how we format commit messages.

Kang Ye this bug - with design documents was coming from your previous commit - I will contact you in slack about this.

**Pull request merged**
